import type { Metadata } from 'next';

import { cn } from '@/lib/cn';
import { pretendard } from '@/assets/fonts';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          pretendard.variable,
          'bg-background font-pretendard text-foreground antialiased typo-body-16'
        )}
      >
        {children}
      </body>
    </html>
  );
}
